# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a76c8b68405e7a21d194e8f98fe17941fc74f529db92d5ecd23849dd49faccb92fd5a9abd2b1ab3736760990ba5bb12c2e5360f4b5f5c3fa1c4eb71f657afe4c

test:
  secret_key_base: b04d6b818ba4574772853bed70aaf3c6e056e282614df5bcbeea52406a2a009ff23d49a211fc32bb2c05022cd1fcc2a002048bf8a59c429031973f0fe0293049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
